__author__ = 'lwz'


from uiwiget import RoundCornerPanel, CompleteDom


def create():
    page = CompleteDom()
    page.setTitle('Logtoeye Report Generated by WebElements')
    page.addHeadLink('/static/css/report.css')

    round_div = RoundCornerPanel()
    page.addChildElement(round_div)

    return page.__str__()


def write(page_str):
    f = open('templates/report_preview.html', 'w')
    f.write(page_str)
    f.flush()
    f.close()
    print 'report created!'


if __name__ == "__main__":
    write(create())