__author__ = 'lwz'

from WebElements import Document, Display


def create():
    page = Document.Document()
    page += Display.Label(text="I'm logtoeye reporter generated by WebElements!")

    # f = open('templates/report_preview.html', 'w')
    # f.write(page.__str__())
    # f.flush()
    # f.close()
    # print 'report created!'
    return page.__str__()

if __name__ == "__main__":
    create()